version: 2

jobs:
  11-bionic:
    docker:
      - image: swift:5.0-bionic
      - image: redis:5
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  bionic-release:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build -c release
workflows:
  version: 2
  tests:
    jobs:
      - 11-bionic
      - bionic-release
