name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test
  thread:
    container: 
      image: vapor/swift:5.1-bionic
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: swift test --sanitize=thread
